### ISSUE TITLE
Zipped adfs, longer file names.

### ISSUE THREAD

**Issue by wronghands** [rsn8887/uae4all2#28] opened 2019-01-26 00:43 UTC
Hi,

I just moved my zipped tosec archive to switch and expected uae4all2 to recognize the adfs inside the zips but it didn't. Would it be too hard to implement zipped adf support like winuae? This would save several GBs of precious sd card space for hoarders! That and maybe being able to see longer file names in the file browser without pressing X as you know tosec file names are inconveniently long. I know I've been asking for a lot of features recently but I hope they make sense. Amazing work on fixing the mouse support so fast btw.

Also, are you having this problem when changing hdfs it just boots to the kickstart screen until you disable HD booting, reset, re-enable and reboot again? Not a big deal but probably a bug there.

Best

**Comment by rsn8887** [comment] 2019-01-26 07:55
I will look into those things you mentioned.

I have heard of this bug you describe before but seem to unable to reproduce it. If you have the time, can you maybe give exact step-by-step instructions on how to reproduce the bug? I wonder if it is related to the kickstart file version you are using (Cloanto DRM’ed files vs. original Amiga roms etc.)

**Comment by rsn8887** [comment] 2019-01-26 13:14
Are you on gbatemp, reddit or Twitter, so I could send you a pm?

**Comment by wronghands** [comment] 2019-01-26 17:33
No but I'm wrong#5094 on discord if you're using it. If not, I'll figure out a way to link my email here while avoiding spam. I'm testing the HD problem with 3.1.4 and 3.1 roms right now and will post a more detailed reply with screenshots very soon.

**Comment by rsn8887** [comment] 2019-01-26 17:39
Ok Discord works

**Comment by rsn8887** [comment] 2019-01-26 17:55
I sent you a friend request.

**Comment by wronghands** [comment] 2019-01-26 20:14
Looks like this is a bit complicated but I'll to explain the best I can. My results are the same with both kickstart 3.1.4 and 3.1. 

This is my 3.1.4 setup:
![314a](https://user-images.githubusercontent.com/16123640/51792237-59564c80-217c-11e9-9446-b4912cd179c1.jpg)
![314b](https://user-images.githubusercontent.com/16123640/51792238-5b201000-217c-11e9-8f4f-def81825861d.jpg)

Kickstart: Official 3.1.4 from Hyperion.
HD Dir: I have to use one in order to access switch's file system.
HD File1: My boot drive named sys.hdf. This is a 100MB, FFS file.
HD File2: 1000.hdf, exactly 1000.00 MBs. This is for whdload files and all the non-system stuff.

This is 3.1:
![31a](https://user-images.githubusercontent.com/16123640/51792239-5d826a00-217c-11e9-85c5-f8664c71340e.jpg)
![31b](https://user-images.githubusercontent.com/16123640/51792242-63784b00-217c-11e9-8ceb-7da1b9fd45cf.jpg)

Kickstart: The common 3.1 one with this MD5 646773759326FBAC3B2311FD8C8793EE. This is the one I'm using with any other uae variant, I never used Cloanto roms before.
HD Dir: Same as above.
HD File1: sys31.hdf. Just a 20MB hdf file with nothing but system on it.
HD File2: Same as above.

This is how my drives normally show up like:
![fine](https://user-images.githubusercontent.com/16123640/51792254-8276dd00-217c-11e9-8a31-3401bb783d48.jpg)

More than one option in the disk options screen cause all hdfs, but not the "HD Dir", to be disabled, probably become unlinked from the runtime config regardless of how it looks fine in the UI:

1 - Deselecting "File1" option, by choosing "dir" or "off".

Assuming this is the state in the beginning...

off Dir [File1]

...doing this in order causes the problem:
1- off Dir [File1]
2- off [Dir] File1
3- off Dir [File1]

This as well:
1- off Dir [File1]
2- [off] Dir File1
3- off Dir [File1]

The drives appear to be inserted but they're not. Early start up menu won't show any drive that uses uaehf.device. It tries to boot from the "HD Dir" if it's set, otherwise shows the kickstart screen.

![dironly](https://user-images.githubusercontent.com/16123640/51792257-8efb3580-217c-11e9-881f-8b76ca1fb021.jpg)

Making it look "OK" in the UI does not fix it but loading the same config (or another one) does. The only apparent way to fix this without loading a new config is to:

- Cause the problem:

1- off Dir [File1]
2- off [Dir] File1
3- off Dir [File1]

- Boot with (R).
- Experience frustration.
- Return to the menu with (-)

- Do the exact thing again:

1- off Dir [File1]
2- off [Dir] File1
3- off Dir [File1]

- Boot with (R).

This is funny because once you get the hang of if you can repeat this loop as many times as you want. IE, you can do the 1-2-3 thing, break the hdfs, reset, do it again to fix it, reset, break it again and so on. It feels like the proper option is only toggled every other reset except with the following case: 

2 - Ejecting any drive (Dir or HDF)

This also happens when starting from the beginning with a freshly loaded uae4all and config. If you eject the "HD Dir", you also lose all the hdfs the same way as above. If you eject any hdf, you lose them all but not the HD Dir. 

Somehow this is a workaround: 

- Eject a drive. Then set... 
- off Dir [File1]
- off [Dir] File1
- off Dir [File1]

- Boot as normal. No reboot is required. This seems to contradict with the other scenario above but maybe you can make sense of it.

3 - Adding a new hdf as "HD File3"

Newly inserted hdf is recognized and it works but the other two are broken as above. "HD Dir" also stays fine.

![1hdf](https://user-images.githubusercontent.com/16123640/51792266-96224380-217c-11e9-81a9-10ccbed4ba05.jpg)

Also another weird issue happened accidentally. Ejecting and re-adding sys.hdf autoloads the default A500 config, probably because i have a config file with the same name (sys.conf). If this is a feature, it wasn't what I intended to do but I guess it's useful for autoloading configs with adfs.

These are the cases I could reliably repeat. A couple other oddities happened left and right while testing this but I couldn't narrow them down to speculate.

**Comment by rsn8887** [comment] 2019-01-26 22:42
Thank you for the detailed report. I think I can fix the issues if I look closer at how hdf preferences are initialized after menu changes.

The config autoload is a feature. You have to make sure your config names are different than your adf or hdf names, otherwise they will be autoloaded.

**Comment by rsn8887** [comment] 2019-02-13 06:36
All this should now (hopefully) be fixed in v1.94.

**Closed by rsn8887** 2019-02-13 06:36 UTC

**Comment by wronghands** [comment] 2019-02-13 08:27
Hey thanks! It's great that you figured out the HDF problem. As for the zipped adf support, I had completely forgotten that adz was a format and was simply talking about actual adfs inside actual zips like the way they're managed through tosec/romvault etc. If that's the same thing, can I simply mass rename my zips to adz so that they work? Would it be too inconvenient design-wise to also to treat such .zips as disks in the drive menu? It's great as it is, I'm just trying to understand the difference in implementation.

**Comment by rsn8887** [comment] 2019-02-13 18:02
Can you try to rename one of your zipped adf disks to .adz and see if it works? It might just work as long as there's not more than one file in the zip archive.

**Comment by rsn8887** [comment] 2019-02-13 18:10
Never mind it seems the gzip format used for .adz is incompatible to the zip format used by WinZIp etc.

**Comment by wronghands** [comment] 2019-02-13 18:23
Yup, it didn't work :)
